In [1]:
import sys,os
import pandas as pd
import numpy as np

In [2]:
go = pd.read_csv("../data/Go.csv")
up = pd.read_csv("../data/Up.csv")
stop = pd.read_csv("../data/Stop.csv")
down= pd.read_csv("../data/Down.csv")

In [3]:
## printing shpes

In [4]:
print(down.shape)
print(up.shape)
print(go.shape)
print(stop.shape)

(25, 65)
(25, 65)
(25, 65)
(25, 65)

In [5]:
stop

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,Sample
0,70.279999,143.800003,169.259995,195.159988,215.339996,227.099991,213.299988,136.259995,122.119995,21.100000,...,19.139999,19.139999,18.799999,18.459999,18.10,17.359999,16.98,17.719999,15.78,1
1,52.820000,65.860001,71.760002,69.260002,60.899998,45.059998,50.680000,90.860001,16.580000,6.260000,...,0.000000,0.000000,3.620000,0.000000,0.00,0.000000,0.00,0.000000,0.00,2
2,117.919998,109.019997,106.220001,101.500000,84.119995,85.959999,202.559998,83.739998,51.699997,39.980000,...,0.000000,3.620000,0.000000,0.000000,0.00,3.620000,5.10,3.620000,3.62,3
3,57.579998,80.720001,78.559998,82.299995,87.099998,90.139999,75.239998,63.939999,151.539993,29.400000,...,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,4
4,45.200001,65.159996,45.639999,42.059998,45.200001,50.160000,53.079998,40.459999,74.279999,25.340000,...,6.260000,6.260000,6.260000,5.100000,5.10,5.100000,3.62,3.620000,3.62,5
5,44.779999,80.139999,98.079994,92.360001,85.040001,71.939995,59.259998,85.040001,22.600000,12.000000,...,0.000000,3.620000,3.620000,0.000000,0.00,0.000000,0.00,0.000000,0.00,6
6,69.439995,74.639999,62.180000,75.320000,71.299995,39.820000,24.539999,12.000000,0.000000,3.620000,...,10.219999,9.559999,8.080000,8.860000,6.26,5.100000,5.10,6.260000,3.62,7
7,67.040001,69.439995,90.199997,96.180000,97.879997,63.840000,49.360001,43.279999,17.719999,8.080000,...,3.620000,3.620000,3.620000,3.620000,0.00,0.000000,0.00,0.000000,0.00,8
8,64.959999,83.739998,88.900002,74.180000,71.299995,73.299995,74.540001,75.759995,46.360001,23.180000,...,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,9
9,51.059998,59.359997,70.000000,72.400002,72.939995,73.019997,70.479996,41.579998,14.920000,12.540000,...,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,10
10,55.840000,75.419998,65.860001,67.239998,66.059998,60.139999,49.099998,35.279999,8.080000,7.240000,...,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,11
11,52.079998,63.520000,59.480000,65.059998,62.059998,51.959999,44.320000,21.400000,11.440000,5.100000,...,0.000000,0.000000,0.000000,0.000000,0.00,3.620000,3.62,0.000000,0.00,12
12,48.279999,74.360001,76.619995,66.159996,57.919998,60.779999,53.699997,52.820000,15.780000,5.100000,...,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,13
13,66.659996,66.360001,76.879997,64.139999,63.739998,56.539997,58.480000,36.200001,8.080000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,14
14,120.339996,108.299995,97.459999,103.599998,103.399994,85.739998,58.820000,16.580000,6.260000,3.620000,...,0.000000,0.000000,0.000000,3.620000,3.62,0.000000,5.10,3.620000,0.00,15
15,42.680000,70.279999,73.299995,77.559998,88.360001,91.079994,88.299995,84.739998,74.099998,41.419998,...,0.000000,0.000000,3.620000,0.000000,0.00,0.000000,0.00,0.000000,0.00,16
16,40.619999,57.000000,67.619995,73.019997,70.479996,63.219997,47.879997,21.100000,15.780000,8.860000,...,5.100000,3.620000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,17
17,59.480000,106.579994,103.860001,111.680000,108.299995,79.299995,34.340000,15.339999,9.559999,7.240000,...,5.100000,3.620000,6.260000,8.860000,12.54,8.080000,6.26,5.100000,0.00,18
18,70.379997,78.639999,65.059998,58.919998,58.480000,13.040000,7.240000,5.100000,3.620000,3.620000,...,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,19
19,69.260002,72.939995,73.220001,53.820000,11.440000,8.080000,6.260000,5.100000,3.620000,3.620000,...,0.000000,0.000000,0.000000,3.620000,0.00,0.000000,0.00,0.000000,0.00,20
20,41.579998,65.260002,52.320000,60.459999,58.480000,57.119999,53.939999,49.239998,17.359999,10.860000,...,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,21
21,54.899998,55.500000,64.239998,55.840000,54.059998,51.199997,27.799999,16.980000,13.540000,12.000000,...,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,3.62,22
22,51.840000,47.879997,51.699997,62.279999,50.160000,44.320000,18.459999,8.080000,3.620000,3.620000,...,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,23
23,54.660000,62.059998,73.019997,79.479996,69.339996,67.519997,49.639999,13.540000,5.100000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.00,24
24,60.020000,65.360001,75.839996,81.900002,62.180000,31.559999,9.559999,3.620000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.00,3.620000,3.62,25

In [6]:
down1 = down.iloc[:,:64]
up1 = up.iloc[:,:64]
go1 = go.iloc[:,:64]
stop1 = stop.iloc[:,:64]

In [7]:
down1 = down1.values.tolist()
up1 = up1.values.tolist()
go1 = go1.values.tolist()
stop1 = stop1.values.tolist()

In [8]:
## cancatenation

In [9]:
V = np.concatenate([down1,up1,go1,stop1])
print(V.shape)

(100, 64)

In [10]:
r1 = [1]*25
r2 = [2]*25
r3 = [3]*25
r4 = [4]*25

In [11]:
r = r1 + r2 + r3 + r4
r = np.array(r)
r

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

## machine learning models

In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
import seaborn as sns
import matplotlib.pyplot as plt

### Logictic Regression

In [13]:
a_train, a_test, b_train, b_test = train_test_split(V,r,train_size=0.8)
print(a_train.shape)
print(a_test.shape)
print(b_train.shape)
print(b_test.shape)

(80, 64)
(20, 64)
(80,)
(20,)

In [18]:

import os
MODELS_DIR = 'models/'
if not os.path.exists(MODELS_DIR):
    os.mkdir(MODELS_DIR)
MODEL_TF = MODELS_DIR + 'model'
MODEL_NO_QUANT_TFLITE = MODELS_DIR + 'model_no_quant.tflite'
MODEL_TFLITE = MODELS_DIR + 'model.tflite'
MODEL_TFLITE_MICRO = MODELS_DIR + 'model.cc'
import tensorflow as tf
##!pip install tensorflow
import tensorflow as tenf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
seed = 1
np.random.seed(seed)
tf.random.set_seed(seed)

# TensorFlow is an open source machine learning library
import tensorflow as tf

# Keras is TensorFlow's high-level API for deep learning
from tensorflow import keras
# Numpy is a math library
import numpy as np
# Pandas is a data manipulation library 
import pandas as pd
# Matplotlib is a graphing library
import matplotlib.pyplot as plt
# Math is Python's math library
import math

# Set seed for experiment reproducibility
seed = 1
np.random.seed(seed)
tf.random.set_seed(seed)

# We'll use Keras to create a simple model architecture
model_1 = tf.keras.Sequential()

model_1.add(keras.layers.Dense(128, activation ='elu' ,input_shape=(a_train.shape[1],)))

# Final layer is 3 neurons, since we want to output into 3 classes
model_1.add(keras.layers.Dense(2, activation='softmax'))

# Compile the model using the standard 'adam' optimizer and Sparse categorical crossentropy
# Compile the model
model_1.compile(loss=tf.keras.losses.sparse_categorical_crossentropy,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])
print(model_1.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 128)               8320

 dense_7 (Dense)             (None, 2)                 258

=================================================================
Total params: 8,578
Trainable params: 8,578
Non-trainable params: 0
_________________________________________________________________
None

In [20]:
# Train the model on our training data while validating on our validation set
##model_1.save(MODEL_TF)
#history_1 = model_1.fit(a_train, b_train, epochs=200, batch_size=100)